### ISSUE TITLE
borrow page 플로우

### ISSUE THREAD

**Issue by westkite1201** [likelion-liquidity/liquidity-front#27]
borrow 페이지에서 borrow 버튼을  눌렀을때  분기 처리 
1. 해당 컬렉션에 예치가 되어 있을 때
2. 해당 컬렉션에 예치가 안되어 있을 때

**Comment by wwdbsh** [comment]
작업 완료하였습니다. pr 확인해주세요~

**Comment by westkite1201** [comment]
확인 하였습니다. 감사합니다
